### ISSUE TITLE
Weird repo dependency error

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#13]
Why does underware require `/var/lib/underware/repo` to be a git repository? 

I'm currently testing a minimal repository so I didn't use `underware repo use` and instead just manually created the files I wanted, this has led to me having to create a `.git` directory in order to actually use underware.

```bash
[root@controller repo]# pwd
/var/lib/underware/repo
[root@controller repo]# ls
config  configure.yaml
[root@controller repo]# underware configure domain
error: 'configure domain' requires a repo. Please run 'repo use'.
[root@controller repo]# mkdir .git
[root@controller repo]# underware configure domain
error: (/var/lib/underware/repo/configure.yaml): did not find expected key while parsing a block mapping at line 119 column 7. Use --trace to view backtrace
```

(ignore the error at the end, I'm experimenting with the contents of `configure.yaml`)

**Comment by bobwhitelock** [comment]
I believe this is related to https://github.com/alces-software/underware/blob/566d1aa483729884fc5c078347b798cb0ae6d94f/lib/underware/dependency.rb#L94

Basically, as part of checking that earlier setup has been done when running other commands that depend on this, at the start of those commands we check that needed files or other effects of the earlier commands are present.

Apparently we decided that the most minimal thing we could check for a Metalware/Underware repo is a `.git` dir, since this is always present for a Git repo (which our real repos always are) and we didn't want to require any given Metalware installation to require any other part of the repo content.

Possibly we could change this to just check for the existence of the `/var/lib/${something}ware/repo` directory for each project - if we did this we would need to remove https://github.com/alces-software/underware/blob/566d1aa483729884fc5c078347b798cb0ae6d94f/scripts/install#L97 - which could have other consequences we would need to check. Or possibly we should depend on part of the repo content which normally exists instead, e.g. `config/domain.yaml` or `configure.yaml` (or both). Or maybe the current behaviour is OK, it depends if pulling in repos from other sources is something we want to support.

**Comment by ColonelPanicks** [comment]
I'm wondering if any of the validation is needed? 

As far as I can see the minimal components required for a repo are:
- `config/domain.yaml`
- `configure.yaml`
- `genders/default`

And just because there is a repo directory doesn't mean these files are present. To me it just seems like a matter of having clearer error messages in the event of required content missing. For example, I had missed out the genders file in my repo so I got the following at the end of configure:
```
error: Failed to render template: /var/lib/underware/repo/genders/default
No such file or directory @ rb_sysopen - /var/lib/underware/repo/genders/default. Use --trace to view backtrace
```
Which seems like enough to communicate the problem.

In terms of no `configure.yaml`, there'd just be no questions to ask. With no `config/domain.yaml` I presume it'd just mean an empty `.config` namespace. All of these things could still be problems whether the directory is a git repo (or even if the files exist).

**Comment by bobwhitelock** [comment]
Yep that all makes sense - I don't know why that original decision to check for the presence of `.git` was made, since we've iterated on and made so many changes to Metalware/Underware since then (@WilliamMcCumstie may know more).

Regardless, replacing that with 3 distinct checks whenever a repo is needed, with checks for each of those needed files sounds like it would be useful, e.g. `A repo containing a 'config/domain.yaml' file is needed to run this command. Please run 'repo use'.` How does that sound?

If we do want to do that, how important would you say this is?

**Comment by bobwhitelock** [comment]
Although `repo use` also expects to be given a Git repo we can clone so we're still semi-dependent on Git if that's used - so we may want to say `...or otherwise obtain a Metalware repo.` instead.

**Comment by ColonelPanicks** [comment]
I don't think even the checking for those files to be present is needed.

The way I see it now is that `repo use` is an optional helper tool but isn't a required step in the process. I think that any non-present config files can just spill out an error message whenever they are to be accessed. What do we have to gain by locking down the program in advance?

For example, letting someone answer their configure questions and then getting told "you need a genders template" is okay. They don't lose their answers and then take the next step of adding a genders template. We can either pre-empt issues or just deal with them when they come up and reactionary seems good to me.

**Comment by bobwhitelock** [comment]
> I don't think even the checking for those files to be present is needed.

Happy to do this if this is determined to be the best option, judicious deleting of stuff related to this should be pretty straightforward. Although re:

> I think that any non-present config files can just spill out an error message whenever they are to be accessed. What do we have to gain by locking down the program in advance?

1. We can fail fast rather than at some (potentially significantly) later time, which doesn't matter so much for `configure` but could for other commands, because they take some time to complete or require re-inputting information.

2. When we do fail we can give a clearer and more accurate error messages as to what the underlying problem is and how you might want to fix it, which would be particularly relevant if we're moving towards productising Metalware/Underware etc. E.g. for someone new to these tools, a message like

  ```
  error: A repo containing a 'config/domain.yaml' file is needed to run this command. Please run 'repo use REPO_URL', or otherwise obtain a Metalware repo, to continue.
  ```
  immediately after running the command seems clearer to me than

  ```
  error: Failed to render template: /var/lib/underware/repo/genders/default
No such file or directory @ rb_sysopen - /var/lib/underware/repo/genders/default. Use --trace to view backtrace
  ```
  after various other output and interaction with Underware. The former is also much more explicit that this is a user error rather than something going wrong in Underware, and should also guide people towards the general way we suggest using the tools (set up a `repo` first, then `configure`, etc.).

**Comment by ColonelPanicks** [comment]
> We can fail fast rather than at some (potentially significantly) later time, which doesn't matter so much for configure but could for other commands, because they take some time to complete or require re-inputting information.

I agree that earlier capturing of potential issues will be helpful but which commands have later dependencies? From what I can see, `configure` writes out answers whether a `genders/default` file is present or not. I trust your judgement though so if you think putting those checks in is the right way to go about it lets go for it.

Going forward, seeing as these files are critical to the running of Underware, it would probably be better to have some default files that ship with Underware. Potentially the exposure of questions will be enough to configure a cluster so things like domain formats can become "hidden internals". Just thinking aloud here but with the dependency on the genders file and formatting for all of the templating, etc that we should control that more.

> When we do fail we can give a clearer and more accurate error messages as to what the underlying problem is and how you might want to fix it, which would be particularly relevant if we're moving towards productising Metalware/Underware etc. E.g. for someone new to these tools, a message like

Absolutely, 100%, it would be great to sanitise a lot of the possible error messages in Underware so please go for it! Also, hiding/removing `--trace` would also be ideal.

**Comment by ColonelPanicks** [comment]
With the recent decision to include the minimal files for the repository within Underware itself I believe this issue has been invalidated (see #15)
