### ISSUE TITLE
Implement Platform Scopes

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#17]
The idea is that this tool will render all the appropriate files to deploy a node on multiple platforms (metal/cloud/virtual/etc). In order to support multiple platforms there are slight differences to configurations based on the chosen platform, for example, the interface for the primary network may be `eth0`, `em1` or something else depending on the platform. 

The platforms that should be included are:
- `kickstart`
- `aws`
- `azure`
- `libvirt`
- `vbox`

In terms of requirements, the platform scope should:
- Set the platform on the fly for the scope (in much the same way that a secondary group would cause inheritance of different configurations in the hierarchy). Currently my thinking is that the level of platform would be pre-node (`domain -> secondary groups -> group -> platform -> node`) or just after node to give it a high precedence of the config values
- Render `[/var/lib/underware/||/etc/underware/]templates/platform-configuration/<platform>/{domain,group,node}/` to `/var/lib/underware/rendered/<platform>/<scope>/platform-configuration`

This will mean that `[/var/lib/underware/||/etc/underware/]config/{kickstart,aws,azure,libvirt,vbox}.yaml` can provide additional configuration and further setup scripts can be created for each platform.

**Comment by bobwhitelock** [comment]
From discussion IRL, plan now is:
- platform config will be merged in after node, as this will both be simpler to implement and mean the platform-specialized node, group, and domain namespaces will all be handled in a consistent way;
- second bullet above is no longer relevant here, and is somewhat obsoleted by the plan in https://github.com/alces-software/underware/issues/19#issuecomment-440744825;
- a single platform config for each platform will exist, at `/opt/underware/data/config/platforms/${platform}.yaml`, and the existence of this file is also what will determine the existence/availability of this platform whenever we need to determine this (such as to determine the valid values for https://github.com/alces-software/underware/issues/24);
- there is no need for a platform-specific configuration process, since all platforms will always be considered and rendered for by the `template` command we can always just ask platform-specific questions in the top-level `configure.yaml` file, if needed.
