### ISSUE TITLE
Implement Group Scopes (and improve rendering scopes in general)

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/underware#20]
Currently the only scopes for rendering are `node` and `no node` (which basically does a domain-level render). Ideally the scoping for rendering will be more flexible to allow for choosing `domain`, `group`, `node` as well as which `platform` (see #17) to render for. 

With changes to how rendering works (see #19) the `group` scope should render the infile once for each group such that there will be multiple output files for each group

E.g. render a cloudformation template for each group (`underware render --groups --platform aws /route/to/my/cloudformation.yaml`), such that the output files would be `group1.yaml`, `group2.yaml`, `group3.yaml`

**Comment by bobwhitelock** [comment]
> Currently the only scopes for rendering are `node` and `no node` (which basically does a domain-level render). Ideally the scoping for rendering will be more flexible to allow for choosing `domain`, `group`, `node` as well as which `platform` (see #17) to render for. 

Internally this essentially sounds like how the scopes work at the moment (apart from the `platform` scope, which doesn't exist yet). There's a top-level root/`alces` scope, where everything can be accessed from, and various nested scopes accessible from this for nodes/groups etc. It's also possible to render things directly against one of these nested scopes, which we do internally in various places within Underware/Metalware.

Possibly the underlying problem with this aspect of this issue is that these scopes aren't currently very exposed to a CLI user - the `render` command, currently the main access point for a user to Underware rendering,  takes a template and an additional optional argument. When this argument is given, the template is rendered against the corresponding node, while when not given the template is rendered against the root/`alces` scope, and there's no way to render against another scope (without modifying your template directly to access this scope, which isn't very flexible).

To resolve this part of this issue, maybe we should modify `render` to allow finding and rendering against any other scope: `underware render node NODE`, `underware render group GROUP`, `underware render root` etc. How does this sound?

> With changes to how rendering works (see #19) the group scope should render the infile once for each group such that there will be multiple output files for each group
> 
> E.g. render a cloudformation template for each group (underware render --groups --platform aws /route/to/my/cloudformation.yaml), such that the output files would be group1.yaml, group2.yaml, group3.yaml

I need to give this part of this issue more thought, but this seems:
1. quite closely related to #17 and #19 (the core issue being: how should rendering of all useful templates across a cluster, and all supported platforms, work);
2. possibly not that closely related to the previous section (allowing arbitrary rendering of individual templates passed on the command-line against a given scope).

Possibly there's more complexity and not as clear a distinction as this, but if you agree that these sound like two distinct use cases we want to handle in different ways, then:

1. seems to be what we need to give some more thought to and discuss how this should work;

2. is just exposing the scopes we already have/will soon have in otherwise similar `render` commands, and so should be fairly straightforward.

Let me know if you have any thoughts on this and let's discuss (1) irl soonish :slightly_smiling_face:.

**Comment by ColonelPanicks** [comment]
I think that perhaps this is an issue that doesn't relate to `render`, with the discussion we had regarding #19 and how this would become a separate `template` command that handles file output alongside the rendering. The handling of "render this file within the scope of each group and output each to a file for the group" and "render this file for all nodes in group and output to a file for each node" seems a lot outside of `render` as it stands.

Equally, the ability to handle the scopes handed into `render` as you mentioned would certainly be beneficial. Being able to go "render this file for this group on this platform" would help with template writing and debugging. 

So to unhelpfully answer pick your options, a bit of 1 and a bit of 2. It's certainly going to involve the additional templating control and platform scopes but would also be a core concept that can be pulled into other commands (like `render`).

Certainly worth a sit-down discussion because I feel like there's a bunch of questions that this one will bring up from the both of us.

**Comment by bobwhitelock** [comment]
From discussion above and meeting earlier we have narrowed down exactly what we need to do for this, and so the different parts of this issue are now better covered by https://github.com/alces-software/underware/issues/23 and https://github.com/alces-software/underware/issues/19, so closing in favour of those.
